# CMake generated Testfile for 
# Source directory: D:/.c_projects/adc/ctcp
# Build directory: D:/.c_projects/adc/ctcp/build_verify
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[headless_smoke]=] "D:/.c_projects/adc/ctcp/build_verify/Debug/ctcp_headless.exe" "--smoke")
  set_tests_properties([=[headless_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;97;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[headless_smoke]=] "D:/.c_projects/adc/ctcp/build_verify/Release/ctcp_headless.exe" "--smoke")
  set_tests_properties([=[headless_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;97;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[headless_smoke]=] "D:/.c_projects/adc/ctcp/build_verify/MinSizeRel/ctcp_headless.exe" "--smoke")
  set_tests_properties([=[headless_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;97;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[headless_smoke]=] "D:/.c_projects/adc/ctcp/build_verify/RelWithDebInfo/ctcp_headless.exe" "--smoke")
  set_tests_properties([=[headless_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;97;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
else()
  add_test([=[headless_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[verify_tools_selftest]=] "D:/anaconda/python.exe" "D:/.c_projects/adc/ctcp/tools/tests/test_verify_tools.py")
  set_tests_properties([=[verify_tools_selftest]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;104;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[verify_tools_selftest]=] "D:/anaconda/python.exe" "D:/.c_projects/adc/ctcp/tools/tests/test_verify_tools.py")
  set_tests_properties([=[verify_tools_selftest]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;104;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[verify_tools_selftest]=] "D:/anaconda/python.exe" "D:/.c_projects/adc/ctcp/tools/tests/test_verify_tools.py")
  set_tests_properties([=[verify_tools_selftest]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;104;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[verify_tools_selftest]=] "D:/anaconda/python.exe" "D:/.c_projects/adc/ctcp/tools/tests/test_verify_tools.py")
  set_tests_properties([=[verify_tools_selftest]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/.c_projects/adc/ctcp/CMakeLists.txt;104;add_test;D:/.c_projects/adc/ctcp/CMakeLists.txt;0;")
else()
  add_test([=[verify_tools_selftest]=] NOT_AVAILABLE)
endif()
