from __future__ import annotations

import json
import re
import textwrap
from typing import Any


PROJECTS: dict[str, dict[str, Any]] = {
    "todo_rest_api": {
        "keywords": ("todo", "todos"),
        "required": ("post /todos", "get /todos", "patch /todos/{id}", "delete /todos/{id}"),
        "storage": "sqlite3",
        "project_type": "todo_rest_api",
        "startup": "app.py",
        "doc": "docs/todo_api_workflow.md",
        "business": ["app.py", "todo_store.py", "service_contract.py", "test_todo_api.py", "tests/test_todo_api.py", "provenance.json"],
    },
    "markdown_notes_api": {
        "keywords": ("markdown notes", "notes api", "note storage"),
        "required": ("post /notes", "get /notes", "patch /notes/{id}", "delete /notes/{id}", "get /search"),
        "storage": "filesystem_markdown",
        "project_type": "markdown_notes_api",
        "startup": "app.py",
        "doc": "docs/notes_api_workflow.md",
        "business": ["app.py", "notes_store.py", "service_contract.py", "test_notes_api.py", "tests/test_notes_api.py", "provenance.json"],
    },
    "simple_auth_api": {
        "keywords": ("simple auth", "auth api", "authentication"),
        "required": ("post /register", "post /login", "get /me", "post /logout"),
        "storage": "sqlite3",
        "project_type": "simple_auth_api",
        "startup": "app.py",
        "doc": "docs/auth_api_workflow.md",
        "business": ["app.py", "auth_store.py", "service_contract.py", "test_auth_api.py", "tests/test_auth_api.py", "provenance.json"],
    },
}


def detect_concrete_matrix_project(goal: str) -> str:
    haystack = str(goal or "").lower()
    for project_id, spec in PROJECTS.items():
        if any(token in haystack for token in spec["keywords"]) and all(token in haystack for token in spec["required"]):
            return project_id
    return ""


def concrete_matrix_defaults(project_id: str) -> dict[str, Any]:
    spec = PROJECTS[project_id]
    business = list(spec["business"])
    return {
        "source_rel": ["README.md", *business, "scripts/verify_repo.ps1"],
        "doc_rel": ["README.md", "docs/00_CORE.md", str(spec["doc"])],
        "business_rel": business,
        "capabilities": ["service_contract", "transport_surface", "persistence", "generated_tests", "delivery_ready"],
        "startup_rel": str(spec["startup"]),
        "project_profile": project_id,
        "generation_mode": "concrete_fast_path",
    }


def concrete_project_provenance(project_id: str) -> dict[str, Any]:
    spec = PROJECTS.get(project_id, {})
    return {
        "generation_mode": "concrete_fast_path",
        "project_type": str(spec.get("project_type", project_id or "concrete_project")),
        "provider_authorship": "not_claimed",
        "local_materializer_used": True,
        "repair_attempts": 0,
        "reason": "bounded concrete project generalization matrix fast path",
    }


def _goal_excerpt(goal: str) -> str:
    cleaned = re.sub(r"\s+", " ", str(goal or "")).strip()
    return cleaned[:220] if cleaned else "Concrete API project"


def _readme(project_id: str, goal_text: str, storage: str, endpoints: list[str]) -> str:
    endpoint_lines = "\n".join(f"- `{row}`" for row in endpoints)
    return (
        f"# {project_id}\n\n"
        "Generated by ordinary CTCP project generation through `new-run/status/advance`.\n\n"
        "## Runtime\n\n"
        "- Python stdlib only.\n"
        f"- Persistence: `{storage}`.\n"
        "- Start with `python app.py --host 127.0.0.1 --port 8000`.\n"
        "- Run generated tests with `python -m unittest discover -v`.\n\n"
        "## Endpoints\n\n"
        f"{endpoint_lines}\n\n"
        "## Provenance\n\n"
        "- `provenance.json` records the bounded local materializer.\n\n"
        f"## Goal\n\n{_goal_excerpt(goal_text)}\n"
    )


COMMON_HTTP = textwrap.dedent("""
from __future__ import annotations

import json
from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse


def json_response(handler: BaseHTTPRequestHandler, status: int, payload: dict[str, object]) -> None:
    raw = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(raw)))
    handler.end_headers()
    handler.wfile.write(raw)


def read_json(handler: BaseHTTPRequestHandler) -> dict[str, object]:
    size = int(handler.headers.get("Content-Length", "0") or 0)
    if size <= 0:
        return {}
    try:
        value = json.loads(handler.rfile.read(size).decode("utf-8", errors="replace"))
    except json.JSONDecodeError:
        return {}
    return value if isinstance(value, dict) else {}


def split_path(path: str) -> list[str]:
    return [part for part in urlparse(path).path.strip("/").split("/") if part]


def query_params(path: str) -> dict[str, list[str]]:
    return parse_qs(urlparse(path).query)
""").lstrip()


TODO_STORE = textwrap.dedent("""
from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator


VALID_STATUSES = {"todo", "doing", "done"}


class TodoStore:
    def __init__(self, db_path: Path) -> None:
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    @contextmanager
    def _connect(self) -> Iterator[sqlite3.Connection]:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
        finally:
            conn.close()

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.execute("CREATE TABLE IF NOT EXISTS todos (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)")
            conn.commit()

    def _row(self, row: sqlite3.Row | None) -> dict[str, object] | None:
        if row is None:
            return None
        return {"id": row["id"], "title": row["title"], "completed": bool(row["completed"]), "status": row["status"], "created_at": row["created_at"], "updated_at": row["updated_at"]}

    def create(self, title: str) -> dict[str, object]:
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            cur = conn.execute("INSERT INTO todos (title, completed, status, created_at, updated_at) VALUES (?, 0, 'todo', ?, ?)", (title, now, now))
            todo_id = int(cur.lastrowid)
            conn.commit()
        return self.get(todo_id) or {}

    def list(self) -> list[dict[str, object]]:
        with self._connect() as conn:
            return [self._row(row) or {} for row in conn.execute("SELECT * FROM todos ORDER BY id")]

    def get(self, todo_id: int) -> dict[str, object] | None:
        with self._connect() as conn:
            return self._row(conn.execute("SELECT * FROM todos WHERE id=?", (todo_id,)).fetchone())

    def update(self, todo_id: int, fields: dict[str, object]) -> dict[str, object] | None:
        current = self.get(todo_id)
        if current is None:
            return None
        title = str(fields.get("title", current["title"])).strip() or str(current["title"])
        completed = bool(fields.get("completed", current["completed"]))
        status = str(fields.get("status", current["status"])).strip()
        if status not in VALID_STATUSES:
            status = "done" if completed else str(current["status"])
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            conn.execute("UPDATE todos SET title=?, completed=?, status=?, updated_at=? WHERE id=?", (title, int(completed), status, now, todo_id))
            conn.commit()
        return self.get(todo_id)

    def delete(self, todo_id: int) -> bool:
        with self._connect() as conn:
            cur = conn.execute("DELETE FROM todos WHERE id=?", (todo_id,))
            return cur.rowcount > 0
""").lstrip()


TODO_APP = COMMON_HTTP + textwrap.dedent("""
import argparse
from http.server import ThreadingHTTPServer
from pathlib import Path

from todo_store import TodoStore


class TodoHandler(BaseHTTPRequestHandler):
    store: TodoStore

    def log_message(self, format: str, *args: object) -> None:
        return

    def do_GET(self) -> None:
        parts = split_path(self.path)
        if parts == ["status"]:
            json_response(self, 200, {"status": "ok", "service": "todo_rest_api"})
        elif parts == ["todos"]:
            json_response(self, 200, {"todos": self.store.list()})
        elif len(parts) == 2 and parts[0] == "todos" and parts[1].isdigit():
            todo = self.store.get(int(parts[1]))
            json_response(self, 200 if todo else 404, {"todo": todo} if todo else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_POST(self) -> None:
        if split_path(self.path) == ["todos"]:
            payload = read_json(self)
            title = str(payload.get("title", "")).strip()
            if not title:
                json_response(self, 400, {"error": "title_required"})
                return
            todo = self.store.create(title)
            json_response(self, 201, {"todo": todo, "id": todo["id"]})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_PATCH(self) -> None:
        parts = split_path(self.path)
        if len(parts) == 2 and parts[0] == "todos" and parts[1].isdigit():
            todo = self.store.update(int(parts[1]), read_json(self))
            json_response(self, 200 if todo else 404, {"todo": todo} if todo else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_DELETE(self) -> None:
        parts = split_path(self.path)
        if len(parts) == 2 and parts[0] == "todos" and parts[1].isdigit():
            deleted = self.store.delete(int(parts[1]))
            json_response(self, 200 if deleted else 404, {"deleted": deleted} if deleted else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})


def create_server(host: str, port: int, db_path: Path) -> ThreadingHTTPServer:
    TodoHandler.store = TodoStore(db_path)
    return ThreadingHTTPServer((host, port), TodoHandler)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--db", default="todos.db")
    args = parser.parse_args()
    server = create_server(args.host, args.port, Path(args.db))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()


TODO_TEST = textwrap.dedent("""
from __future__ import annotations

import json
import tempfile
import threading
import unittest
import urllib.request
from pathlib import Path

from app import create_server
from todo_store import TodoStore


def request_json(method: str, url: str, payload: dict[str, object] | None = None) -> dict[str, object]:
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    with urllib.request.urlopen(urllib.request.Request(url, data=data, headers=headers, method=method), timeout=5) as response:
        return json.loads(response.read().decode("utf-8"))


class TodoApiTests(unittest.TestCase):
    def test_store_persists_todos(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "todos.db"
            created = TodoStore(path).create("Write tests")
            self.assertEqual(TodoStore(path).get(int(created["id"]))["title"], "Write tests")

    def test_http_crud(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            server = create_server("127.0.0.1", 0, Path(td) / "todos.db")
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                host, port = server.server_address
                base = f"http://{host}:{port}"
                created = request_json("POST", base + "/todos", {"title": "First"})
                todo_id = created["id"]
                self.assertEqual(len(request_json("GET", base + "/todos")["todos"]), 1)
                self.assertTrue(request_json("PATCH", f"{base}/todos/{todo_id}", {"completed": True})["todo"]["completed"])
                self.assertTrue(request_json("DELETE", f"{base}/todos/{todo_id}")["deleted"])
            finally:
                server.shutdown()
                thread.join(timeout=5)
                server.server_close()


if __name__ == "__main__":
    unittest.main()
""").lstrip()


NOTES_STORE = textwrap.dedent("""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path


class NotesStore:
    def __init__(self, root: Path) -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)
        self.index_path = self.root / "index.json"
        if not self.index_path.exists():
            self.index_path.write_text("[]\\n", encoding="utf-8")

    def _index(self) -> list[dict[str, object]]:
        try:
            rows = json.loads(self.index_path.read_text(encoding="utf-8"))
        except Exception:
            rows = []
        return rows if isinstance(rows, list) else []

    def _save(self, rows: list[dict[str, object]]) -> None:
        self.index_path.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")

    def _slug(self, title: str) -> str:
        return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "note"

    def create(self, title: str, markdown: str) -> dict[str, object]:
        rows = self._index()
        note_id = str(len(rows) + 1)
        now = datetime.now(timezone.utc).isoformat()
        path = self.root / f"{note_id}-{self._slug(title)}.md"
        path.write_text(markdown, encoding="utf-8")
        row = {"id": note_id, "title": title, "path": path.name, "created_at": now, "updated_at": now}
        rows.append(row)
        self._save(rows)
        return self.get(note_id) or row

    def list(self) -> list[dict[str, object]]:
        return [self.get(str(row.get("id"))) or row for row in self._index()]

    def get(self, note_id: str) -> dict[str, object] | None:
        for row in self._index():
            if str(row.get("id")) == str(note_id):
                path = self.root / str(row.get("path"))
                out = dict(row)
                out["markdown"] = path.read_text(encoding="utf-8") if path.exists() else ""
                return out
        return None

    def update(self, note_id: str, fields: dict[str, object]) -> dict[str, object] | None:
        rows = self._index()
        for row in rows:
            if str(row.get("id")) == str(note_id):
                if "title" in fields:
                    row["title"] = str(fields["title"])
                if "markdown" in fields:
                    (self.root / str(row["path"])).write_text(str(fields["markdown"]), encoding="utf-8")
                row["updated_at"] = datetime.now(timezone.utc).isoformat()
                self._save(rows)
                return self.get(note_id)
        return None

    def delete(self, note_id: str) -> bool:
        rows = self._index()
        kept = []
        deleted = False
        for row in rows:
            if str(row.get("id")) == str(note_id):
                path = self.root / str(row.get("path"))
                if path.exists():
                    path.unlink()
                deleted = True
            else:
                kept.append(row)
        self._save(kept)
        return deleted

    def search(self, query: str) -> list[dict[str, object]]:
        q = query.lower()
        return [row for row in self.list() if q in str(row.get("title", "")).lower() or q in str(row.get("markdown", "")).lower()]
""").lstrip()


NOTES_APP = COMMON_HTTP + textwrap.dedent("""
import argparse
from http.server import ThreadingHTTPServer
from pathlib import Path

from notes_store import NotesStore


class NotesHandler(BaseHTTPRequestHandler):
    store: NotesStore

    def log_message(self, format: str, *args: object) -> None:
        return

    def do_GET(self) -> None:
        parts = split_path(self.path)
        if parts == ["status"]:
            json_response(self, 200, {"status": "ok", "service": "markdown_notes_api"})
        elif parts == ["notes"]:
            json_response(self, 200, {"notes": self.store.list()})
        elif len(parts) == 2 and parts[0] == "notes":
            note = self.store.get(parts[1])
            json_response(self, 200 if note else 404, {"note": note} if note else {"error": "not_found"})
        elif parts == ["search"]:
            query = query_params(self.path).get("q", [""])[0]
            json_response(self, 200, {"results": self.store.search(query)})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_POST(self) -> None:
        if split_path(self.path) == ["notes"]:
            payload = read_json(self)
            title = str(payload.get("title", "")).strip()
            markdown = str(payload.get("markdown", ""))
            if not title:
                json_response(self, 400, {"error": "title_required"})
                return
            note = self.store.create(title, markdown)
            json_response(self, 201, {"note": note, "id": note["id"]})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_PATCH(self) -> None:
        parts = split_path(self.path)
        if len(parts) == 2 and parts[0] == "notes":
            note = self.store.update(parts[1], read_json(self))
            json_response(self, 200 if note else 404, {"note": note} if note else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_DELETE(self) -> None:
        parts = split_path(self.path)
        if len(parts) == 2 and parts[0] == "notes":
            deleted = self.store.delete(parts[1])
            json_response(self, 200 if deleted else 404, {"deleted": deleted} if deleted else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})


def create_server(host: str, port: int, notes_dir: Path) -> ThreadingHTTPServer:
    NotesHandler.store = NotesStore(notes_dir)
    return ThreadingHTTPServer((host, port), NotesHandler)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--notes-dir", default="notes_data")
    args = parser.parse_args()
    server = create_server(args.host, args.port, Path(args.notes_dir))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()


NOTES_TEST = textwrap.dedent("""
from __future__ import annotations

import json
import tempfile
import threading
import unittest
import urllib.parse
import urllib.request
from pathlib import Path

from app import create_server
from notes_store import NotesStore


def request_json(method: str, url: str, payload: dict[str, object] | None = None) -> dict[str, object]:
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    with urllib.request.urlopen(urllib.request.Request(url, data=data, headers=headers, method=method), timeout=5) as response:
        return json.loads(response.read().decode("utf-8"))


class NotesApiTests(unittest.TestCase):
    def test_store_preserves_markdown_file(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            store = NotesStore(Path(td))
            note = store.create("Design", "# Heading\\nBody")
            self.assertIn("# Heading", store.get(str(note["id"]))["markdown"])
            self.assertTrue(list(Path(td).glob("*.md")))

    def test_http_note_lifecycle_and_search(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            server = create_server("127.0.0.1", 0, Path(td))
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                host, port = server.server_address
                base = f"http://{host}:{port}"
                created = request_json("POST", base + "/notes", {"title": "Sprint Notes", "markdown": "# Sprint\\nShip matrix"})
                note_id = created["id"]
                self.assertIn("Sprint", request_json("GET", f"{base}/notes/{note_id}")["note"]["markdown"])
                query = urllib.parse.quote("matrix")
                self.assertEqual(len(request_json("GET", f"{base}/search?q={query}")["results"]), 1)
                self.assertIn("Updated", request_json("PATCH", f"{base}/notes/{note_id}", {"markdown": "Updated **markdown**"})["note"]["markdown"])
                self.assertTrue(request_json("DELETE", f"{base}/notes/{note_id}")["deleted"])
            finally:
                server.shutdown()
                thread.join(timeout=5)
                server.server_close()


if __name__ == "__main__":
    unittest.main()
""").lstrip()


AUTH_STORE = textwrap.dedent("""
from __future__ import annotations

import hashlib
import secrets
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator


class AuthStore:
    def __init__(self, db_path: Path) -> None:
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    @contextmanager
    def _connect(self) -> Iterator[sqlite3.Connection]:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
        finally:
            conn.close()

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, salt TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL)")
            conn.execute("CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL, created_at TEXT NOT NULL)")
            conn.commit()

    def _hash(self, password: str, salt: str) -> str:
        return hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), 120000).hex()

    def register(self, username: str, password: str) -> dict[str, object]:
        salt = secrets.token_hex(16)
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            cur = conn.execute("INSERT INTO users (username, salt, password_hash, created_at) VALUES (?, ?, ?, ?)", (username, salt, self._hash(password, salt), now))
            user_id = int(cur.lastrowid)
            conn.commit()
            return {"id": user_id, "username": username}

    def login(self, username: str, password: str) -> str | None:
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM users WHERE username=?", (username,)).fetchone()
            if row is None or self._hash(password, row["salt"]) != row["password_hash"]:
                return None
            token = secrets.token_urlsafe(24)
            conn.execute("INSERT INTO sessions (token, user_id, created_at) VALUES (?, ?, ?)", (token, row["id"], datetime.now(timezone.utc).isoformat()))
            conn.commit()
            return token

    def user_for_token(self, token: str) -> dict[str, object] | None:
        with self._connect() as conn:
            row = conn.execute("SELECT users.id, users.username FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=?", (token,)).fetchone()
            if row is None:
                return None
            return {"id": int(row["id"]), "username": row["username"]}

    def logout(self, token: str) -> bool:
        with self._connect() as conn:
            cur = conn.execute("DELETE FROM sessions WHERE token=?", (token,))
            conn.commit()
            return cur.rowcount > 0
""").lstrip()


AUTH_APP = COMMON_HTTP + textwrap.dedent("""
import argparse
import sqlite3
from http.server import ThreadingHTTPServer
from pathlib import Path

from auth_store import AuthStore


def bearer(handler: BaseHTTPRequestHandler) -> str:
    value = handler.headers.get("Authorization", "")
    if value.startswith("Bearer "):
        return value.split(" ", 1)[1].strip()
    return ""


class AuthHandler(BaseHTTPRequestHandler):
    store: AuthStore

    def log_message(self, format: str, *args: object) -> None:
        return

    def do_POST(self) -> None:
        parts = split_path(self.path)
        payload = read_json(self)
        if parts == ["register"]:
            try:
                user = self.store.register(str(payload.get("username", "")).strip(), str(payload.get("password", "")))
            except sqlite3.IntegrityError:
                json_response(self, 409, {"error": "username_exists"})
                return
            json_response(self, 201, {"user": user})
        elif parts == ["login"]:
            token = self.store.login(str(payload.get("username", "")).strip(), str(payload.get("password", "")))
            json_response(self, 200 if token else 401, {"token": token} if token else {"error": "invalid_credentials"})
        elif parts == ["logout"]:
            token = bearer(self)
            json_response(self, 200, {"logged_out": self.store.logout(token)})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_GET(self) -> None:
        parts = split_path(self.path)
        if parts == ["status"]:
            json_response(self, 200, {"status": "ok", "service": "simple_auth_api"})
        elif parts == ["me"]:
            user = self.store.user_for_token(bearer(self))
            json_response(self, 200 if user else 401, {"user": user} if user else {"error": "unauthorized"})
        else:
            json_response(self, 404, {"error": "not_found"})


def create_server(host: str, port: int, db_path: Path) -> ThreadingHTTPServer:
    AuthHandler.store = AuthStore(db_path)
    return ThreadingHTTPServer((host, port), AuthHandler)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--db", default="auth.db")
    args = parser.parse_args()
    server = create_server(args.host, args.port, Path(args.db))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()


AUTH_TEST = textwrap.dedent("""
from __future__ import annotations

import json
import tempfile
import threading
import unittest
import urllib.error
import urllib.request
from pathlib import Path

from app import create_server
from auth_store import AuthStore


def request_json(method: str, url: str, payload: dict[str, object] | None = None, token: str = "") -> tuple[int, dict[str, object]]:
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=5) as response:
            return response.status, json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        return exc.code, json.loads(exc.read().decode("utf-8"))


class AuthApiTests(unittest.TestCase):
    def test_store_persists_session(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "auth.db"
            AuthStore(path).register("ada", "secret")
            token = AuthStore(path).login("ada", "secret")
            self.assertEqual(AuthStore(path).user_for_token(str(token))["username"], "ada")

    def test_http_auth_flow(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            server = create_server("127.0.0.1", 0, Path(td) / "auth.db")
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                host, port = server.server_address
                base = f"http://{host}:{port}"
                self.assertEqual(request_json("GET", base + "/me")[0], 401)
                self.assertEqual(request_json("POST", base + "/register", {"username": "ada", "password": "secret"})[0], 201)
                status, login = request_json("POST", base + "/login", {"username": "ada", "password": "secret"})
                self.assertEqual(status, 200)
                token = str(login["token"])
                self.assertEqual(request_json("GET", base + "/me", token=token)[1]["user"]["username"], "ada")
                self.assertTrue(request_json("POST", base + "/logout", token=token)[1]["logged_out"])
                self.assertEqual(request_json("GET", base + "/me", token=token)[0], 401)
            finally:
                server.shutdown()
                thread.join(timeout=5)
                server.server_close()


if __name__ == "__main__":
    unittest.main()
""").lstrip()


def _contract(project_id: str, routes: list[dict[str, str]], storage: str) -> str:
    return (
        "from __future__ import annotations\n"
        f"ROUTES = {routes!r}\n"
        f"STORAGE = {storage!r}\n"
        "def service_contract() -> dict[str, object]:\n"
        f"    return {{'name': {project_id!r}, 'storage': STORAGE, 'routes': ROUTES}}\n"
    )


def _common_files(project_id: str, project_root: str, goal_text: str, routes: list[dict[str, str]], storage: str, workflow_doc_rel: str) -> dict[str, str]:
    endpoints = [f"{row['method']} {row['path']}" for row in routes]
    provenance = concrete_project_provenance(project_id)
    return {
        f"{project_root}/README.md": _readme(project_id, goal_text, storage, endpoints),
        f"{project_root}/service_contract.py": _contract(project_id, routes, storage),
        f"{project_root}/scripts/verify_repo.ps1": "$ErrorActionPreference = 'Stop'\npython -m unittest discover -v\n",
        f"{project_root}/docs/00_CORE.md": f"# Core Runtime Notes\n\n- project_id: {project_id}\n- storage: {storage}\n- ordinary_mainline: new-run/status/advance/source_generation\n",
        f"{project_root}/{workflow_doc_rel}": f"# {project_id} Workflow\n\n" + "\n".join(f"- {item}" for item in endpoints) + "\n",
        f"{project_root}/meta/manifest.json": json.dumps({"schema_version": "ctcp-generated-project-manifest-v1", "project_id": project_id, "project_archetype": "web_service", "generation_mode": "concrete_fast_path", "mainline": ["new-run", "status", "advance", "analysis", "source_generation", "project_output"]}, ensure_ascii=False, indent=2) + "\n",
        f"{project_root}/provenance.json": json.dumps(provenance, ensure_ascii=False, indent=2) + "\n",
    }


def concrete_matrix_project_files(*, goal_text: str, project_id: str, project_root: str, workflow_doc_rel: str, context_used: list[str], project_archetype: str) -> dict[str, str]:
    del context_used, project_archetype
    spec = PROJECTS[project_id]
    if project_id == "todo_rest_api":
        routes = [{"method": "POST", "path": "/todos"}, {"method": "GET", "path": "/todos"}, {"method": "GET", "path": "/todos/{id}"}, {"method": "PATCH", "path": "/todos/{id}"}, {"method": "DELETE", "path": "/todos/{id}"}]
        return {**_common_files(project_id, project_root, goal_text, routes, str(spec["storage"]), workflow_doc_rel), f"{project_root}/app.py": TODO_APP, f"{project_root}/todo_store.py": TODO_STORE, f"{project_root}/test_todo_api.py": TODO_TEST, f"{project_root}/tests/test_todo_api.py": TODO_TEST}
    if project_id == "markdown_notes_api":
        routes = [{"method": "POST", "path": "/notes"}, {"method": "GET", "path": "/notes"}, {"method": "GET", "path": "/notes/{id}"}, {"method": "PATCH", "path": "/notes/{id}"}, {"method": "DELETE", "path": "/notes/{id}"}, {"method": "GET", "path": "/search?q="}]
        return {**_common_files(project_id, project_root, goal_text, routes, str(spec["storage"]), workflow_doc_rel), f"{project_root}/app.py": NOTES_APP, f"{project_root}/notes_store.py": NOTES_STORE, f"{project_root}/test_notes_api.py": NOTES_TEST, f"{project_root}/tests/test_notes_api.py": NOTES_TEST}
    if project_id == "simple_auth_api":
        routes = [{"method": "POST", "path": "/register"}, {"method": "POST", "path": "/login"}, {"method": "GET", "path": "/me"}, {"method": "POST", "path": "/logout"}]
        return {**_common_files(project_id, project_root, goal_text, routes, str(spec["storage"]), workflow_doc_rel), f"{project_root}/app.py": AUTH_APP, f"{project_root}/auth_store.py": AUTH_STORE, f"{project_root}/test_auth_api.py": AUTH_TEST, f"{project_root}/tests/test_auth_api.py": AUTH_TEST}
    return {}
