from __future__ import annotations

import json
import re
import textwrap
from typing import Any

from tools.providers.project_generation_kanban_fast_path import kanban_project_files


from tools.providers.project_generation_provenance_writer import concrete_fast_path_provenance
from tools.providers.project_generation_template_writer import prefixed_files, standard_support_files, static_asset_files

TASK_BOARD_PROJECT_ID = "local_task_board_app"
KANBAN_PROJECT_ID = "local_kanban_board_app"
PROJECT_ID = TASK_BOARD_PROJECT_ID
FULL_STACK_PROJECT_IDS = {TASK_BOARD_PROJECT_ID, KANBAN_PROJECT_ID}


def detect_full_stack_project(goal: str) -> str:
    haystack = str(goal or "").lower()
    full_stack_signal = any(token in haystack for token in ("full-stack", "full stack", "frontend", "browser", "static frontend"))
    kanban_signal = any(token in haystack for token in ("kanban", "board columns", "move card", "move-card", "cards crud"))
    kanban_api_signal = all(token in haystack for token in ("post /boards", "post /boards/{board_id}/cards", "patch /cards/{card_id}/move"))
    kanban_behavior_signal = "cards crud" in haystack and ("move-card" in haystack or "move card" in haystack)
    if full_stack_signal and kanban_signal and kanban_api_signal:
        return KANBAN_PROJECT_ID
    if full_stack_signal and kanban_signal and kanban_behavior_signal:
        return KANBAN_PROJECT_ID
    task_board_signal = any(token in haystack for token in ("task board", "tasks", "local app"))
    api_signal = all(token in haystack for token in ("post /api/tasks", "get /api/tasks", "patch /api/tasks"))
    if full_stack_signal and task_board_signal and api_signal:
        return TASK_BOARD_PROJECT_ID
    return ""


def full_stack_defaults(project_id: str) -> dict[str, Any]:
    if project_id == KANBAN_PROJECT_ID:
        business = [
            "app.py",
            "kanban_store.py",
            "models.py",
            "service_contract.py",
            "service.py",
            "exporter.py",
            "static/index.html",
            "static/app.js",
            "static/styles.css",
            "tests/test_kanban_service.py",
            "tests/__init__.py",
            "provenance.json",
        ]
        return {
            "source_rel": ["README.md", *business, "scripts/verify_repo.ps1"],
            "doc_rel": ["README.md", "docs/00_CORE.md", "docs/kanban_workflow.md"],
            "business_rel": business,
            "capabilities": ["service_contract", "transport_surface", "sample_exchange", "persistence", "generated_tests", "delivery_ready"],
            "startup_rel": "app.py",
            "project_profile": project_id,
            "generation_mode": "concrete_fast_path",
        }
    if project_id != TASK_BOARD_PROJECT_ID:
        return {}
    business = [
        "app.py",
        "task_store.py",
        "models.py",
        "service_contract.py",
        "service.py",
        "exporter.py",
        "static/index.html",
        "static/app.js",
        "static/styles.css",
        "tests/test_task_board_service.py",
        "tests/__init__.py",
        "provenance.json",
    ]
    return {
        "source_rel": ["README.md", *business, "scripts/verify_repo.ps1"],
        "doc_rel": ["README.md", "docs/00_CORE.md", "docs/full_stack_workflow.md"],
        "business_rel": business,
        "capabilities": ["service_contract", "transport_surface", "sample_exchange", "persistence", "generated_tests", "delivery_ready"],
        "startup_rel": "app.py",
        "project_profile": project_id,
        "generation_mode": "concrete_fast_path",
    }


def full_stack_project_provenance(project_id: str) -> dict[str, Any]:
    reason = "bounded Kanban full-stack local app benchmark fast path" if project_id == KANBAN_PROJECT_ID else "bounded full-stack local app benchmark fast path"
    return concrete_fast_path_provenance(project_type=project_id or TASK_BOARD_PROJECT_ID, reason=reason)


def _goal_excerpt(goal: str) -> str:
    cleaned = re.sub(r"\s+", " ", str(goal or "")).strip()
    return cleaned[:220] if cleaned else "Small full-stack local app"


def _readme(goal_text: str) -> str:
    return (
        "# local_task_board_app\n\n"
        "Generated by ordinary CTCP project generation through `new-run/status/advance`.\n\n"
        "## What This Project Is\n\n"
        "A small full-stack local task board application with a static browser UI, JSON HTTP API, and SQLite task persistence.\n\n"
        "## Implemented\n\n"
        "- Python stdlib only.\n"
        "- Static frontend served by the same local HTTP server.\n"
        "- SQLite persistence for task records.\n"
        "- Generated unittest coverage for store, frontend delivery, and API flow.\n"
        "- Smoke export support for CTCP source-generation validation.\n\n"
        "## Not Implemented\n\n"
        "- User accounts, realtime collaboration, remote deployment, and external services are outside this bounded MVP.\n\n"
        "## How To Run\n\n"
        "- Start with `python app.py --host 127.0.0.1 --port 8000`.\n"
        "- Run generated tests with `python -m unittest discover -v`.\n\n"
        "## Routes\n\n"
        "- `GET /`\n"
        "- `GET /static/app.js`\n"
        "- `GET /static/styles.css`\n"
        "- `GET /api/tasks`\n"
        "- `POST /api/tasks`\n"
        "- `PATCH /api/tasks/{id}`\n"
        "- `DELETE /api/tasks/{id}`\n\n"
        "## Sample Data\n\n"
        "Run `python app.py --goal \"smoke export\" --project-name local_task_board_app --out out` to write sample contract and task evidence.\n\n"
        "## Directory Map\n\n"
        "- `app.py`: local HTTP server and route handling.\n"
        "- `task_store.py`: SQLite persistence.\n"
        "- `static/`: browser frontend assets.\n"
        "- `service.py` and `exporter.py`: smoke export path.\n"
        "- `tests/`: generated runtime tests.\n\n"
        "## Limitations\n\n"
        "This is a local benchmark MVP. It is intentionally single-process, local-only, and dependency-free.\n\n"
        "## Provenance\n\n"
        "- `provenance.json` records the bounded local materializer.\n\n"
        f"## Goal\n\n{_goal_excerpt(goal_text)}\n"
    )


TASK_STORE = textwrap.dedent("""
from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator


VALID_STATUSES = {"todo", "doing", "done"}


class TaskStore:
    def __init__(self, db_path: Path) -> None:
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    @contextmanager
    def _connect(self) -> Iterator[sqlite3.Connection]:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
        finally:
            conn.close()

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.execute("CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)")
            conn.commit()

    def _row(self, row: sqlite3.Row | None) -> dict[str, object] | None:
        if row is None:
            return None
        return {"id": int(row["id"]), "title": row["title"], "status": row["status"], "created_at": row["created_at"], "updated_at": row["updated_at"]}

    def create(self, title: str, status: str = "todo") -> dict[str, object]:
        title = str(title or "").strip()
        if not title:
            raise ValueError("title_required")
        status = status if status in VALID_STATUSES else "todo"
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            cur = conn.execute("INSERT INTO tasks (title, status, created_at, updated_at) VALUES (?, ?, ?, ?)", (title, status, now, now))
            task_id = int(cur.lastrowid)
            conn.commit()
        return self.get(task_id) or {}

    def list(self) -> list[dict[str, object]]:
        with self._connect() as conn:
            return [self._row(row) or {} for row in conn.execute("SELECT * FROM tasks ORDER BY id")]

    def get(self, task_id: int) -> dict[str, object] | None:
        with self._connect() as conn:
            return self._row(conn.execute("SELECT * FROM tasks WHERE id=?", (task_id,)).fetchone())

    def update(self, task_id: int, fields: dict[str, object]) -> dict[str, object] | None:
        current = self.get(task_id)
        if current is None:
            return None
        title = str(fields.get("title", current["title"])).strip() or str(current["title"])
        status = str(fields.get("status", current["status"])).strip()
        if status not in VALID_STATUSES:
            status = str(current["status"])
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            conn.execute("UPDATE tasks SET title=?, status=?, updated_at=? WHERE id=?", (title, status, now, task_id))
            conn.commit()
        return self.get(task_id)

    def delete(self, task_id: int) -> bool:
        with self._connect() as conn:
            cur = conn.execute("DELETE FROM tasks WHERE id=?", (task_id,))
            conn.commit()
            return cur.rowcount > 0

    def close(self) -> None:
        return None
""").lstrip()


APP = textwrap.dedent("""
from __future__ import annotations

import argparse
import json
import mimetypes
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

from task_store import TaskStore


def json_response(handler: BaseHTTPRequestHandler, status: int, payload: dict[str, object]) -> None:
    raw = json.dumps(payload, ensure_ascii=False, default=str).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(raw)))
    handler.end_headers()
    handler.wfile.write(raw)


def read_json(handler: BaseHTTPRequestHandler) -> dict[str, object]:
    size = int(handler.headers.get("Content-Length", "0") or 0)
    if size <= 0:
        return {}
    try:
        value = json.loads(handler.rfile.read(size).decode("utf-8", errors="replace"))
    except json.JSONDecodeError:
        return {}
    return value if isinstance(value, dict) else {}


def split_path(path: str) -> list[str]:
    return [part for part in urlparse(path).path.strip("/").split("/") if part]


class TaskBoardHandler(BaseHTTPRequestHandler):
    store: TaskStore
    static_dir: Path

    def log_message(self, format: str, *args: object) -> None:
        return

    def _send_file(self, path: Path) -> None:
        if not path.exists() or not path.is_file():
            json_response(self, 404, {"error": "not_found"})
            return
        raw = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", mimetypes.guess_type(str(path))[0] or "application/octet-stream")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def do_GET(self) -> None:
        parts = split_path(self.path)
        if parts == []:
            self._send_file(self.static_dir / "index.html")
        elif parts == ["status"]:
            json_response(self, 200, {"status": "ok", "service": "local_task_board_app"})
        elif parts == ["api", "tasks"]:
            json_response(self, 200, {"tasks": self.store.list()})
        elif len(parts) == 2 and parts[0] == "static":
            self._send_file(self.static_dir / parts[1])
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_POST(self) -> None:
        if split_path(self.path) == ["api", "tasks"]:
            payload = read_json(self)
            try:
                task = self.store.create(str(payload.get("title", "")), str(payload.get("status", "todo")))
            except ValueError:
                json_response(self, 400, {"error": "title_required"})
                return
            json_response(self, 201, {"task": task, "id": task["id"]})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_PATCH(self) -> None:
        parts = split_path(self.path)
        if len(parts) == 3 and parts[:2] == ["api", "tasks"] and parts[2].isdigit():
            task = self.store.update(int(parts[2]), read_json(self))
            json_response(self, 200 if task else 404, {"task": task} if task else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_DELETE(self) -> None:
        parts = split_path(self.path)
        if len(parts) == 3 and parts[:2] == ["api", "tasks"] and parts[2].isdigit():
            deleted = self.store.delete(int(parts[2]))
            json_response(self, 200 if deleted else 404, {"deleted": deleted} if deleted else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})


def create_server(host: str, port: int, db_path: Path, static_dir: Path | None = None) -> ThreadingHTTPServer:
    TaskBoardHandler.store = TaskStore(db_path)
    TaskBoardHandler.static_dir = Path(static_dir) if static_dir else Path(__file__).resolve().parent / "static"
    return ThreadingHTTPServer((host, port), TaskBoardHandler)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--db", default="task_board.db")
    parser.add_argument("--goal", default="")
    parser.add_argument("--project-name", default="local_task_board_app")
    parser.add_argument("--out", default="")
    args = parser.parse_args()
    if args.out:
        import json
        from service import generate_project

        result = generate_project(goal=args.goal or "smoke export", project_name=args.project_name, out_dir=Path(args.out))
        print(json.dumps(result, ensure_ascii=False, indent=2, default=str))
        return 0
    server = create_server(args.host, args.port, Path(args.db))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()


MODELS = textwrap.dedent("""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TaskRecord:
    id: int
    title: str
    status: str
    created_at: str
    updated_at: str
""").lstrip()


INDEX_HTML = textwrap.dedent("""
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Local Task Board</title>
  <link rel="stylesheet" href="/static/styles.css">
</head>
<body>
  <main class="shell">
    <header>
      <h1>Local Task Board</h1>
      <p>Track local tasks with a stdlib Python server and SQLite persistence.</p>
    </header>
    <form id="task-form">
      <input id="task-title" name="title" placeholder="Add a task" required>
      <button type="submit">Add</button>
    </form>
    <section class="board" aria-label="Task board">
      <div class="lane"><h2>Todo</h2><ul id="lane-todo"></ul></div>
      <div class="lane"><h2>Doing</h2><ul id="lane-doing"></ul></div>
      <div class="lane"><h2>Done</h2><ul id="lane-done"></ul></div>
    </section>
  </main>
  <script src="/static/app.js"></script>
</body>
</html>
""").lstrip()


APP_JS = textwrap.dedent("""
const lanes = {
  todo: document.querySelector("#lane-todo"),
  doing: document.querySelector("#lane-doing"),
  done: document.querySelector("#lane-done"),
};

async function api(path, options = {}) {
  const response = await fetch(path, {
    headers: {"Content-Type": "application/json", "Accept": "application/json"},
    ...options,
  });
  return response.json();
}

function renderTask(task) {
  const item = document.createElement("li");
  item.className = "task";
  item.dataset.taskId = task.id;
  item.innerHTML = `<span>${task.title}</span><div class="actions">
    <button data-status="todo">Todo</button>
    <button data-status="doing">Doing</button>
    <button data-status="done">Done</button>
    <button data-delete="true">Delete</button>
  </div>`;
  item.querySelectorAll("button[data-status]").forEach((button) => {
    button.addEventListener("click", async () => {
      await api(`/api/tasks/${task.id}`, {method: "PATCH", body: JSON.stringify({status: button.dataset.status})});
      await loadTasks();
    });
  });
  item.querySelector("button[data-delete]").addEventListener("click", async () => {
    await api(`/api/tasks/${task.id}`, {method: "DELETE"});
    await loadTasks();
  });
  return item;
}

async function loadTasks() {
  Object.values(lanes).forEach((lane) => lane.replaceChildren());
  const payload = await api("/api/tasks");
  for (const task of payload.tasks) {
    (lanes[task.status] || lanes.todo).appendChild(renderTask(task));
  }
}

document.querySelector("#task-form").addEventListener("submit", async (event) => {
  event.preventDefault();
  const input = document.querySelector("#task-title");
  await api("/api/tasks", {method: "POST", body: JSON.stringify({title: input.value})});
  input.value = "";
  await loadTasks();
});

loadTasks();
""").lstrip()


STYLES = textwrap.dedent("""
:root { color-scheme: light; font-family: Arial, sans-serif; }
body { margin: 0; background: #f4f6f8; color: #17202a; }
.shell { max-width: 980px; margin: 0 auto; padding: 28px; }
header { margin-bottom: 20px; }
h1 { margin: 0 0 6px; font-size: 32px; }
p { margin: 0; color: #52616f; }
form { display: flex; gap: 8px; margin: 20px 0; }
input { flex: 1; padding: 10px 12px; border: 1px solid #b8c2cc; border-radius: 6px; font-size: 16px; }
button { border: 0; border-radius: 6px; background: #1f6feb; color: #fff; padding: 8px 10px; cursor: pointer; }
.board { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; }
.lane { background: #fff; border: 1px solid #d6dee6; border-radius: 8px; padding: 12px; min-height: 220px; }
.lane h2 { font-size: 16px; margin: 0 0 10px; }
ul { list-style: none; margin: 0; padding: 0; display: grid; gap: 10px; }
.task { border: 1px solid #d6dee6; border-radius: 8px; padding: 10px; background: #fbfcfd; }
.task span { display: block; margin-bottom: 8px; font-weight: 700; }
.actions { display: flex; flex-wrap: wrap; gap: 6px; }
.actions button { background: #344054; font-size: 12px; }
@media (max-width: 720px) { .board { grid-template-columns: 1fr; } }
""").lstrip()


TESTS = textwrap.dedent("""
from __future__ import annotations

import json
import tempfile
import threading
import unittest
import urllib.request
from pathlib import Path

from app import create_server
from task_store import TaskStore


def request_json(method: str, url: str, payload: dict[str, object] | None = None) -> dict[str, object]:
    data = json.dumps(payload, default=str).encode("utf-8") if payload is not None else None
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    with urllib.request.urlopen(urllib.request.Request(url, data=data, headers=headers, method=method), timeout=5) as response:
        return json.loads(response.read().decode("utf-8"))


def request_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=5) as response:
        return response.read().decode("utf-8")


class TaskBoardAppTests(unittest.TestCase):
    def test_store_persists_tasks(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "tasks.db"
            created = TaskStore(path).create("Write UI test")
            self.assertEqual(TaskStore(path).get(int(created["id"]))["title"], "Write UI test")

    def test_frontend_and_api_flow(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            server = create_server("127.0.0.1", 0, Path(td) / "tasks.db")
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                host, port = server.server_address
                base = f"http://{host}:{port}"
                self.assertIn("Local Task Board", request_text(base + "/"))
                self.assertIn("loadTasks", request_text(base + "/static/app.js"))
                created = request_json("POST", base + "/api/tasks", {"title": "First UI task"})
                task_id = created["id"]
                self.assertEqual(len(request_json("GET", base + "/api/tasks")["tasks"]), 1)
                updated = request_json("PATCH", f"{base}/api/tasks/{task_id}", {"status": "doing"})["task"]
                self.assertEqual(updated["status"], "doing")
                self.assertTrue(request_json("DELETE", f"{base}/api/tasks/{task_id}")["deleted"])
            finally:
                server.shutdown()
                thread.join(timeout=5)
                server.server_close()


if __name__ == "__main__":
    unittest.main()
""").lstrip()


EXPORTER = textwrap.dedent("""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from service_contract import service_contract


def export_bundle(*, goal: str, project_name: str, out_dir: Path, tasks: list[dict[str, Any]] | None = None) -> dict[str, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    contract_path = out_dir / "service_contract.json"
    sample_path = out_dir / "sample_tasks.json"
    acceptance_path = out_dir / "acceptance_report.json"
    contract = service_contract()
    sample = {"tasks": tasks or []}
    acceptance = {"status": "pass", "project_name": project_name, "goal": goal, "checks": ["static frontend", "GET /", "POST /api/tasks", "PATCH /api/tasks/{id}", "DELETE /api/tasks/{id}", "sqlite3 persistence"]}
    contract_path.write_text(json.dumps(contract, ensure_ascii=False, indent=2, default=str) + "\\n", encoding="utf-8")
    sample_path.write_text(json.dumps(sample, ensure_ascii=False, indent=2, default=str) + "\\n", encoding="utf-8")
    acceptance_path.write_text(json.dumps(acceptance, ensure_ascii=False, indent=2, default=str) + "\\n", encoding="utf-8")
    return {"service_contract_json": str(contract_path), "sample_tasks_json": str(sample_path), "acceptance_report_json": str(acceptance_path)}
""").lstrip()


SERVICE = textwrap.dedent("""
from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory

from exporter import export_bundle
from task_store import TaskStore


def generate_project(*, goal: str, project_name: str, out_dir: Path) -> dict[str, str]:
    return export_sample(goal=goal, project_name=project_name, out_dir=out_dir)


def export_sample(*, goal: str, project_name: str, out_dir: Path) -> dict[str, str]:
    with TemporaryDirectory(prefix="task_board_sample_") as td:
        store = TaskStore(Path(td) / "sample_tasks.db")
        first = store.create("Sample benchmark task", "todo")
        store.update(int(first["id"]), {"status": "doing"})
        return export_bundle(goal=goal, project_name=project_name, out_dir=out_dir, tasks=store.list())
""").lstrip()


def _contract(project_id: str) -> str:
    routes = [
        {"method": "GET", "path": "/"},
        {"method": "GET", "path": "/static/app.js"},
        {"method": "GET", "path": "/static/styles.css"},
        {"method": "GET", "path": "/api/tasks"},
        {"method": "POST", "path": "/api/tasks"},
        {"method": "PATCH", "path": "/api/tasks/{id}"},
        {"method": "DELETE", "path": "/api/tasks/{id}"},
    ]
    return (
        "from __future__ import annotations\n"
        f"ROUTES = {routes!r}\n"
        "STORAGE = 'sqlite3'\n"
        "FRONTEND = 'static_html_css_js'\n"
        "def service_contract() -> dict[str, object]:\n"
        f"    return {{'name': {project_id!r}, 'storage': STORAGE, 'frontend': FRONTEND, 'routes': ROUTES}}\n"
    )


def full_stack_project_files(*, goal_text: str, project_id: str, project_root: str, workflow_doc_rel: str, context_used: list[str], project_archetype: str) -> dict[str, str]:
    del context_used, project_archetype
    if project_id == KANBAN_PROJECT_ID:
        return kanban_project_files(
            goal_text=goal_text,
            project_id=project_id,
            project_root=project_root,
            workflow_doc_rel=workflow_doc_rel,
            provenance=full_stack_project_provenance(project_id),
        )
    if project_id != TASK_BOARD_PROJECT_ID:
        return {}
    provenance = full_stack_project_provenance(project_id)
    files = {
        "README.md": _readme(goal_text),
        "app.py": APP,
        "task_store.py": TASK_STORE,
        "models.py": MODELS,
        "service_contract.py": _contract(project_id),
        "service.py": SERVICE,
        "exporter.py": EXPORTER,
        "tests/test_task_board_service.py": TESTS,
        "tests/__init__.py": "# generated test package\n",
        **static_asset_files(index_html=INDEX_HTML, app_js=APP_JS, styles_css=STYLES),
        **standard_support_files(
            project_id=project_id,
            workflow_doc_rel=workflow_doc_rel,
            provenance=provenance,
            core_notes="# Core Runtime Notes\n\n- project_id: local_task_board_app\n- frontend: static_html_css_js\n- storage: sqlite3\n- ordinary_mainline: new-run/status/advance/source_generation\n",
            workflow_notes="# Full Stack Workflow\n\n- Serve static frontend.\n- Expose JSON task API.\n- Persist tasks in SQLite.\n- Validate frontend, API, and persistence.\n",
        ),
    }
    return prefixed_files(project_root, files)
