from __future__ import annotations

import textwrap

from tools.providers.project_generation_template_writer import prefixed_files, standard_support_files, static_asset_files


def _goal_excerpt(goal: str) -> str:
    cleaned = " ".join(str(goal or "").split())
    return cleaned[:220] if cleaned else "Full-stack Kanban board benchmark request"


def _kanban_readme(goal_text: str) -> str:
    return (
        "# local_kanban_board_app\n\n"
        "Generated by ordinary CTCP project generation through `new-run/status/advance`.\n\n"
        "## What This Project Is\n\n"
        "A small full-stack Kanban board with a static browser UI, JSON HTTP API, and SQLite persistence for boards and cards.\n\n"
        "## Implemented\n\n"
        "- Python stdlib only.\n"
        "- Three board columns: `todo`, `doing`, and `done`.\n"
        "- Board creation plus card create/list/move/update/delete.\n"
        "- Static frontend that renders columns and cards and calls the backend with `fetch()`.\n"
        "- Generated unittest coverage for store, frontend delivery, API flow, and card movement.\n"
        "- Smoke export support for CTCP source-generation validation.\n\n"
        "## Not Implemented\n\n"
        "- User accounts, drag-and-drop, realtime collaboration, remote deployment, and external services are outside this bounded MVP.\n\n"
        "## How To Run\n\n"
        "- Start with `python app.py --host 127.0.0.1 --port 8000`.\n"
        "- Run generated tests with `python -m unittest discover -v`.\n"
        "- Run a smoke export with `python app.py --goal \"smoke export\" --project-name local_kanban_board_app --out out`.\n\n"
        "## Routes\n\n"
        "- `GET /`\n"
        "- `GET /static/app.js`\n"
        "- `GET /static/styles.css`\n"
        "- `POST /boards`\n"
        "- `GET /boards`\n"
        "- `POST /boards/{board_id}/cards`\n"
        "- `GET /boards/{board_id}/cards`\n"
        "- `PATCH /cards/{card_id}/move`\n"
        "- `PATCH /cards/{card_id}`\n"
        "- `DELETE /cards/{card_id}`\n\n"
        "## Sample Data\n\n"
        "The smoke export writes `service_contract.json`, `sample_cards.json`, and `acceptance_report.json`.\n\n"
        "## Directory Map\n\n"
        "- `app.py`: local HTTP server and route handling.\n"
        "- `kanban_store.py`: SQLite boards/cards persistence.\n"
        "- `static/`: browser frontend assets.\n"
        "- `service.py` and `exporter.py`: smoke export path.\n"
        "- `tests/`: generated runtime tests.\n\n"
        "## Limitations\n\n"
        "This is a local benchmark MVP. It is intentionally single-process, local-only, and dependency-free.\n\n"
        "## Provenance\n\n"
        "- `provenance.json` records the bounded local materializer.\n\n"
        f"## Goal\n\n{_goal_excerpt(goal_text)}\n"
    )


KANBAN_MODELS = textwrap.dedent("""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BoardRecord:
    id: int
    name: str


@dataclass(frozen=True)
class CardRecord:
    id: int
    board_id: int
    title: str
    description: str
    column: str
    position: int
    created_at: str
    updated_at: str
""").lstrip()


def _kanban_contract(project_id: str) -> str:
    routes = [
        {"method": "GET", "path": "/"},
        {"method": "GET", "path": "/static/app.js"},
        {"method": "GET", "path": "/static/styles.css"},
        {"method": "POST", "path": "/boards"},
        {"method": "GET", "path": "/boards"},
        {"method": "POST", "path": "/boards/{board_id}/cards"},
        {"method": "GET", "path": "/boards/{board_id}/cards"},
        {"method": "PATCH", "path": "/cards/{card_id}/move"},
        {"method": "PATCH", "path": "/cards/{card_id}"},
        {"method": "DELETE", "path": "/cards/{card_id}"},
    ]
    return (
        "from __future__ import annotations\n"
        f"ROUTES = {routes!r}\n"
        "STORAGE = 'sqlite3'\n"
        "FRONTEND = 'static_html_css_js'\n"
        "COLUMNS = ['todo', 'doing', 'done']\n"
        "def service_contract() -> dict[str, object]:\n"
        f"    return {{'name': {project_id!r}, 'storage': STORAGE, 'frontend': FRONTEND, 'columns': COLUMNS, 'routes': ROUTES}}\n"
    )


KANBAN_EXPORTER = textwrap.dedent("""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from service_contract import service_contract


def export_bundle(*, goal: str, project_name: str, out_dir: Path, boards: list[dict[str, Any]] | None = None, cards: list[dict[str, Any]] | None = None) -> dict[str, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    contract_path = out_dir / "service_contract.json"
    sample_path = out_dir / "sample_cards.json"
    acceptance_path = out_dir / "acceptance_report.json"
    contract = service_contract()
    sample = {"boards": boards or [], "cards": cards or []}
    acceptance = {"status": "pass", "project_name": project_name, "goal": goal, "checks": ["static frontend", "POST /boards", "POST /boards/{board_id}/cards", "PATCH /cards/{card_id}/move", "DELETE /cards/{card_id}", "sqlite3 persistence"]}
    contract_path.write_text(json.dumps(contract, ensure_ascii=False, indent=2, default=str) + "\\n", encoding="utf-8")
    sample_path.write_text(json.dumps(sample, ensure_ascii=False, indent=2, default=str) + "\\n", encoding="utf-8")
    acceptance_path.write_text(json.dumps(acceptance, ensure_ascii=False, indent=2, default=str) + "\\n", encoding="utf-8")
    return {"service_contract_json": str(contract_path), "sample_cards_json": str(sample_path), "acceptance_report_json": str(acceptance_path)}
""").lstrip()


KANBAN_SERVICE = textwrap.dedent("""
from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory

from exporter import export_bundle
from kanban_store import KanbanStore


def generate_project(*, goal: str, project_name: str, out_dir: Path) -> dict[str, str]:
    return export_sample(goal=goal, project_name=project_name, out_dir=out_dir)


def export_sample(*, goal: str, project_name: str, out_dir: Path) -> dict[str, str]:
    with TemporaryDirectory(prefix="kanban_sample_") as td:
        store = KanbanStore(Path(td) / "sample_kanban.db")
        board = store.create_board("Sample Kanban Board")
        first = store.create_card(int(board["id"]), "Sample card", "move through columns", "todo")
        store.move_card(int(first["id"]), "doing", 1)
        return export_bundle(goal=goal, project_name=project_name, out_dir=out_dir, boards=store.list_boards(), cards=store.list_cards(int(board["id"])))
""").lstrip()


KANBAN_STORE = textwrap.dedent("""
from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator


ALLOWED_COLUMNS = {"todo", "doing", "done"}


class KanbanStore:
    def __init__(self, db_path: Path) -> None:
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    @contextmanager
    def _connect(self) -> Iterator[sqlite3.Connection]:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
        finally:
            conn.close()

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.execute("CREATE TABLE IF NOT EXISTS boards (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL)")
            conn.execute("CREATE TABLE IF NOT EXISTS cards (id INTEGER PRIMARY KEY AUTOINCREMENT, board_id INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, column_name TEXT NOT NULL, position INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(board_id) REFERENCES boards(id))")
            conn.commit()

    def _board(self, row: sqlite3.Row | None) -> dict[str, object] | None:
        return None if row is None else {"id": int(row["id"]), "name": row["name"]}

    def _card(self, row: sqlite3.Row | None) -> dict[str, object] | None:
        if row is None:
            return None
        return {"id": int(row["id"]), "board_id": int(row["board_id"]), "title": row["title"], "description": row["description"], "column": row["column_name"], "position": int(row["position"]), "created_at": row["created_at"], "updated_at": row["updated_at"]}

    def create_board(self, name: str) -> dict[str, object]:
        name = str(name or "").strip() or "Kanban Board"
        with self._connect() as conn:
            cur = conn.execute("INSERT INTO boards (name) VALUES (?)", (name,))
            board_id = int(cur.lastrowid)
            conn.commit()
        return self.get_board(board_id) or {}

    def list_boards(self) -> list[dict[str, object]]:
        with self._connect() as conn:
            return [self._board(row) or {} for row in conn.execute("SELECT * FROM boards ORDER BY id")]

    def get_board(self, board_id: int) -> dict[str, object] | None:
        with self._connect() as conn:
            return self._board(conn.execute("SELECT * FROM boards WHERE id=?", (board_id,)).fetchone())

    def create_card(self, board_id: int, title: str, description: str = "", column: str = "todo") -> dict[str, object] | None:
        if self.get_board(board_id) is None:
            return None
        title = str(title or "").strip()
        if not title:
            raise ValueError("title_required")
        column = column if column in ALLOWED_COLUMNS else "todo"
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            row = conn.execute("SELECT COALESCE(MAX(position), 0) + 1 FROM cards WHERE board_id=? AND column_name=?", (board_id, column)).fetchone()
            position = int(row[0] if row else 1)
            cur = conn.execute("INSERT INTO cards (board_id, title, description, column_name, position, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)", (board_id, title, str(description or ""), column, position, now, now))
            card_id = int(cur.lastrowid)
            conn.commit()
        return self.get_card(card_id)

    def list_cards(self, board_id: int) -> list[dict[str, object]]:
        with self._connect() as conn:
            return [self._card(row) or {} for row in conn.execute("SELECT * FROM cards WHERE board_id=? ORDER BY column_name, position, id", (board_id,))]

    def get_card(self, card_id: int) -> dict[str, object] | None:
        with self._connect() as conn:
            return self._card(conn.execute("SELECT * FROM cards WHERE id=?", (card_id,)).fetchone())

    def update_card(self, card_id: int, fields: dict[str, object]) -> dict[str, object] | None:
        current = self.get_card(card_id)
        if current is None:
            return None
        title = str(fields.get("title", current["title"])).strip() or str(current["title"])
        description = str(fields.get("description", current["description"]))
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            conn.execute("UPDATE cards SET title=?, description=?, updated_at=? WHERE id=?", (title, description, now, card_id))
            conn.commit()
        return self.get_card(card_id)

    def move_card(self, card_id: int, column: str, position: int | None = None) -> dict[str, object] | None:
        if column not in ALLOWED_COLUMNS or self.get_card(card_id) is None:
            return None
        if position is None or position < 1:
            position = 1
        now = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            conn.execute("UPDATE cards SET column_name=?, position=?, updated_at=? WHERE id=?", (column, int(position), now, card_id))
            conn.commit()
        return self.get_card(card_id)

    def delete_card(self, card_id: int) -> bool:
        with self._connect() as conn:
            cur = conn.execute("DELETE FROM cards WHERE id=?", (card_id,))
            conn.commit()
            return cur.rowcount > 0

    def close(self) -> None:
        return None
""").lstrip()


KANBAN_APP = textwrap.dedent("""
from __future__ import annotations

import argparse
import json
import mimetypes
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

from kanban_store import KanbanStore


def json_response(handler: BaseHTTPRequestHandler, status: int, payload: dict[str, object]) -> None:
    raw = json.dumps(payload, ensure_ascii=False, default=str).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(raw)))
    handler.end_headers()
    handler.wfile.write(raw)


def read_json(handler: BaseHTTPRequestHandler) -> dict[str, object]:
    size = int(handler.headers.get("Content-Length", "0") or 0)
    if size <= 0:
        return {}
    try:
        value = json.loads(handler.rfile.read(size).decode("utf-8", errors="replace"))
    except json.JSONDecodeError:
        return {}
    return value if isinstance(value, dict) else {}


def split_path(path: str) -> list[str]:
    return [part for part in urlparse(path).path.strip("/").split("/") if part]


class KanbanHandler(BaseHTTPRequestHandler):
    store: KanbanStore
    static_dir: Path

    def log_message(self, format: str, *args: object) -> None:
        return

    def _send_file(self, path: Path) -> None:
        if not path.exists() or not path.is_file():
            json_response(self, 404, {"error": "not_found"})
            return
        raw = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", mimetypes.guess_type(str(path))[0] or "application/octet-stream")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def do_GET(self) -> None:
        parts = split_path(self.path)
        if parts == []:
            self._send_file(self.static_dir / "index.html")
        elif parts == ["status"]:
            json_response(self, 200, {"status": "ok", "service": "local_kanban_board_app"})
        elif parts == ["boards"]:
            json_response(self, 200, {"boards": self.store.list_boards()})
        elif len(parts) == 3 and parts[0] == "boards" and parts[1].isdigit() and parts[2] == "cards":
            json_response(self, 200, {"cards": self.store.list_cards(int(parts[1]))})
        elif len(parts) == 2 and parts[0] == "static":
            self._send_file(self.static_dir / parts[1])
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_POST(self) -> None:
        parts = split_path(self.path)
        payload = read_json(self)
        if parts == ["boards"]:
            board = self.store.create_board(str(payload.get("name", "")))
            json_response(self, 201, {"board": board, "id": board["id"]})
        elif len(parts) == 3 and parts[0] == "boards" and parts[1].isdigit() and parts[2] == "cards":
            try:
                card = self.store.create_card(int(parts[1]), str(payload.get("title", "")), str(payload.get("description", "")), str(payload.get("column", "todo")))
            except ValueError:
                json_response(self, 400, {"error": "title_required"})
                return
            json_response(self, 201 if card else 404, {"card": card, "id": card["id"]} if card else {"error": "board_not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_PATCH(self) -> None:
        parts = split_path(self.path)
        payload = read_json(self)
        if len(parts) == 3 and parts[0] == "cards" and parts[1].isdigit() and parts[2] == "move":
            card = self.store.move_card(int(parts[1]), str(payload.get("column", "")), int(payload.get("position", 1) or 1))
            json_response(self, 200 if card else 404, {"card": card} if card else {"error": "not_found"})
        elif len(parts) == 2 and parts[0] == "cards" and parts[1].isdigit():
            card = self.store.update_card(int(parts[1]), payload)
            json_response(self, 200 if card else 404, {"card": card} if card else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})

    def do_DELETE(self) -> None:
        parts = split_path(self.path)
        if len(parts) == 2 and parts[0] == "cards" and parts[1].isdigit():
            deleted = self.store.delete_card(int(parts[1]))
            json_response(self, 200 if deleted else 404, {"deleted": deleted} if deleted else {"error": "not_found"})
        else:
            json_response(self, 404, {"error": "not_found"})


def create_server(host: str, port: int, db_path: Path, static_dir: Path | None = None) -> ThreadingHTTPServer:
    KanbanHandler.store = KanbanStore(db_path)
    KanbanHandler.static_dir = Path(static_dir) if static_dir else Path(__file__).resolve().parent / "static"
    return ThreadingHTTPServer((host, port), KanbanHandler)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--db", default="kanban_board.db")
    parser.add_argument("--goal", default="")
    parser.add_argument("--project-name", default="local_kanban_board_app")
    parser.add_argument("--out", default="")
    args = parser.parse_args()
    if args.out:
        import json
        from service import generate_project

        result = generate_project(goal=args.goal or "smoke export", project_name=args.project_name, out_dir=Path(args.out))
        print(json.dumps(result, ensure_ascii=False, indent=2, default=str))
        return 0
    server = create_server(args.host, args.port, Path(args.db))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()


KANBAN_INDEX_HTML = textwrap.dedent("""
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Local Kanban Board</title>
  <link rel="stylesheet" href="/static/styles.css">
</head>
<body>
  <main class="shell">
    <header>
      <h1 id="board-title">Local Kanban Board</h1>
      <p>Move cards through Todo, Doing, and Done with local SQLite persistence.</p>
    </header>
    <form id="card-form">
      <input id="card-title" name="title" placeholder="Card title" required>
      <input id="card-description" name="description" placeholder="Description">
      <button type="submit">Create card</button>
    </form>
    <section class="board" aria-label="Kanban board">
      <div class="column" data-column="todo"><h2>Todo</h2><ul id="column-todo"></ul></div>
      <div class="column" data-column="doing"><h2>Doing</h2><ul id="column-doing"></ul></div>
      <div class="column" data-column="done"><h2>Done</h2><ul id="column-done"></ul></div>
    </section>
  </main>
  <script src="/static/app.js"></script>
</body>
</html>
""").lstrip()


KANBAN_APP_JS = textwrap.dedent("""
let activeBoardId = null;
const columns = {
  todo: document.querySelector("#column-todo"),
  doing: document.querySelector("#column-doing"),
  done: document.querySelector("#column-done"),
};

async function api(path, options = {}) {
  const response = await fetch(path, {
    headers: {"Content-Type": "application/json", "Accept": "application/json"},
    ...options,
  });
  return response.json();
}

async function ensureBoard() {
  const payload = await api("/boards");
  if (payload.boards.length > 0) {
    activeBoardId = payload.boards[0].id;
    document.querySelector("#board-title").textContent = payload.boards[0].name;
    return;
  }
  const created = await api("/boards", {method: "POST", body: JSON.stringify({name: "Local Kanban Board"})});
  activeBoardId = created.id;
  document.querySelector("#board-title").textContent = created.board.name;
}

function cardNode(card) {
  const item = document.createElement("li");
  item.className = "card";
  item.dataset.cardId = card.id;
  item.innerHTML = `<strong>${card.title}</strong><p>${card.description || ""}</p><div class="actions">
    <button data-move="todo">Todo</button>
    <button data-move="doing">Doing</button>
    <button data-move="done">Done</button>
    <button data-delete="true">Delete</button>
  </div>`;
  item.querySelectorAll("button[data-move]").forEach((button) => {
    button.addEventListener("click", async () => {
      await moveCard(card.id, button.dataset.move);
    });
  });
  item.querySelector("button[data-delete]").addEventListener("click", async () => {
    await api(`/cards/${card.id}`, {method: "DELETE"});
    await loadCards();
  });
  return item;
}

async function moveCard(cardId, column) {
  await api(`/cards/${cardId}/move`, {method: "PATCH", body: JSON.stringify({column, position: 1})});
  await loadCards();
}

async function loadCards() {
  Object.values(columns).forEach((column) => column.replaceChildren());
  const payload = await api(`/boards/${activeBoardId}/cards`);
  for (const card of payload.cards) {
    (columns[card.column] || columns.todo).appendChild(cardNode(card));
  }
}

document.querySelector("#card-form").addEventListener("submit", async (event) => {
  event.preventDefault();
  const title = document.querySelector("#card-title");
  const description = document.querySelector("#card-description");
  await api(`/boards/${activeBoardId}/cards`, {method: "POST", body: JSON.stringify({title: title.value, description: description.value, column: "todo"})});
  title.value = "";
  description.value = "";
  await loadCards();
});

ensureBoard().then(loadCards);
""").lstrip()


KANBAN_STYLES = textwrap.dedent("""
:root { color-scheme: light; font-family: Arial, sans-serif; }
body { margin: 0; background: #eef2f6; color: #1f2933; }
.shell { max-width: 1120px; margin: 0 auto; padding: 28px; }
header { margin-bottom: 20px; }
h1 { margin: 0 0 6px; font-size: 32px; }
p { margin: 0; color: #52616f; }
form { display: grid; grid-template-columns: 1fr 1fr auto; gap: 8px; margin: 20px 0; }
input { padding: 10px 12px; border: 1px solid #b8c2cc; border-radius: 6px; font-size: 16px; }
button { border: 0; border-radius: 6px; background: #14532d; color: #fff; padding: 8px 10px; cursor: pointer; }
.board { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; }
.column { background: #fff; border: 1px solid #d6dee6; border-radius: 8px; padding: 12px; min-height: 260px; }
.column h2 { font-size: 16px; margin: 0 0 10px; }
ul { list-style: none; margin: 0; padding: 0; display: grid; gap: 10px; }
.card { border: 1px solid #d6dee6; border-radius: 8px; padding: 10px; background: #fbfcfd; }
.card strong { display: block; margin-bottom: 6px; }
.card p { margin-bottom: 8px; }
.actions { display: flex; flex-wrap: wrap; gap: 6px; }
.actions button { background: #344054; font-size: 12px; }
@media (max-width: 760px) { form, .board { grid-template-columns: 1fr; } }
""").lstrip()


KANBAN_TESTS = textwrap.dedent("""
from __future__ import annotations

import json
import tempfile
import threading
import unittest
import urllib.request
from pathlib import Path

from app import create_server
from kanban_store import KanbanStore


def request_json(method: str, url: str, payload: dict[str, object] | None = None) -> dict[str, object]:
    data = json.dumps(payload, default=str).encode("utf-8") if payload is not None else None
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    with urllib.request.urlopen(urllib.request.Request(url, data=data, headers=headers, method=method), timeout=5) as response:
        return json.loads(response.read().decode("utf-8"))


def request_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=5) as response:
        return response.read().decode("utf-8")


class KanbanAppTests(unittest.TestCase):
    def test_store_moves_and_persists_card(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "kanban.db"
            store = KanbanStore(path)
            board = store.create_board("Roadmap")
            card = store.create_card(int(board["id"]), "Ship benchmark", "validate kanban", "todo")
            moved = store.move_card(int(card["id"]), "doing", 1)
            self.assertEqual(moved["column"], "doing")
            self.assertEqual(KanbanStore(path).get_card(int(card["id"]))["column"], "doing")

    def test_frontend_and_api_flow(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            server = create_server("127.0.0.1", 0, Path(td) / "kanban.db")
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                host, port = server.server_address
                base = f"http://{host}:{port}"
                self.assertIn("Local Kanban Board", request_text(base + "/"))
                self.assertIn("fetch(", request_text(base + "/static/app.js"))
                board = request_json("POST", base + "/boards", {"name": "Runtime Board"})
                board_id = board["id"]
                created = request_json("POST", f"{base}/boards/{board_id}/cards", {"title": "First card", "description": "runtime", "column": "todo"})
                card_id = created["id"]
                self.assertEqual(len(request_json("GET", f"{base}/boards/{board_id}/cards")["cards"]), 1)
                moved = request_json("PATCH", f"{base}/cards/{card_id}/move", {"column": "doing", "position": 1})["card"]
                self.assertEqual(moved["column"], "doing")
                updated = request_json("PATCH", f"{base}/cards/{card_id}", {"title": "Updated card"})["card"]
                self.assertEqual(updated["title"], "Updated card")
                self.assertTrue(request_json("DELETE", f"{base}/cards/{card_id}")["deleted"])
            finally:
                server.shutdown()
                thread.join(timeout=5)
                server.server_close()


if __name__ == "__main__":
    unittest.main()
""").lstrip()



def kanban_project_files(*, goal_text: str, project_id: str, project_root: str, workflow_doc_rel: str, provenance: dict[str, object]) -> dict[str, str]:
    files = {
        "README.md": _kanban_readme(goal_text),
        "app.py": KANBAN_APP,
        "kanban_store.py": KANBAN_STORE,
        "models.py": KANBAN_MODELS,
        "service_contract.py": _kanban_contract(project_id),
        "service.py": KANBAN_SERVICE,
        "exporter.py": KANBAN_EXPORTER,
        "tests/test_kanban_service.py": KANBAN_TESTS,
        "tests/__init__.py": "# generated test package\n",
        **static_asset_files(index_html=KANBAN_INDEX_HTML, app_js=KANBAN_APP_JS, styles_css=KANBAN_STYLES),
        **standard_support_files(
            project_id=project_id,
            workflow_doc_rel=workflow_doc_rel,
            provenance=provenance,
            core_notes="# Core Runtime Notes\n\n- project_id: local_kanban_board_app\n- frontend: static_html_css_js\n- storage: sqlite3\n- ordinary_mainline: new-run/status/advance/source_generation\n",
            workflow_notes="# Kanban Full Stack Workflow\n\n- Serve static frontend.\n- Expose JSON board/card API.\n- Persist boards and cards in SQLite.\n- Validate frontend, API, card movement, and persistence.\n",
        ),
    }
    return prefixed_files(project_root, files)
