from __future__ import annotations

import json
import textwrap
from typing import Any

from tools.providers.project_generation_provenance_writer import concrete_fast_path_provenance
from tools.providers.project_generation_template_writer import prefixed_files, standard_support_files


PROJECTS: dict[str, dict[str, Any]] = {
    "csv_expense_analyzer": {
        "keywords": ("csv expense", "expense analyzer", "category totals", "monthly totals"),
        "required": ("--input", "--output", "sample_expenses.csv"),
        "startup": "expense_analyzer.py",
        "doc": "docs/expense_analyzer_workflow.md",
        "business": ["expense_analyzer.py", "tests/test_expense_analyzer.py", "sample_expenses.csv", "provenance.json"],
        "description": "CSV Expense Analyzer CLI",
    },
    "log_analyzer_cli": {
        "keywords": ("log analyzer", "parse log", "top error", "info/warn/error"),
        "required": ("--input", "--output", "sample.log"),
        "startup": "log_analyzer.py",
        "doc": "docs/log_analyzer_workflow.md",
        "business": ["log_analyzer.py", "tests/test_log_analyzer.py", "sample.log", "provenance.json"],
        "description": "Log Analyzer CLI",
    },
    "text_utils_package": {
        "keywords": ("text utilities", "text utils", "slugify", "word_count", "extract_keywords"),
        "required": ("normalize_whitespace", "python package"),
        "startup": "text_utils/__init__.py",
        "doc": "docs/text_utils_workflow.md",
        "business": ["text_utils/__init__.py", "text_utils/core.py", "tests/test_text_utils.py", "provenance.json"],
        "description": "Text Utilities Python Package",
    },
    "terminal_quiz_game": {
        "keywords": ("terminal quiz", "quiz game", "question loading", "test-mode"),
        "required": ("--questions", "--answers", "sample_questions.json"),
        "startup": "quiz_game.py",
        "doc": "docs/quiz_game_workflow.md",
        "business": ["quiz_game.py", "tests/test_quiz_game.py", "sample_questions.json", "provenance.json"],
        "description": "Terminal Quiz Game",
    },
}


def detect_non_web_project(goal: str) -> str:
    haystack = str(goal or "").lower()
    for project_id, spec in PROJECTS.items():
        if any(token in haystack for token in spec["keywords"]) and all(token in haystack for token in spec["required"]):
            return project_id
    return ""


def non_web_defaults(project_id: str) -> dict[str, Any]:
    spec = PROJECTS[project_id]
    business = list(spec["business"])
    return {
        "source_rel": ["README.md", *business, "scripts/verify_repo.ps1"],
        "doc_rel": ["README.md", "docs/00_CORE.md", str(spec["doc"])],
        "business_rel": business,
        "capabilities": ["cli_or_package_runtime", "generated_tests", "local_deterministic_validation", "delivery_ready"],
        "startup_rel": str(spec["startup"]),
        "project_profile": project_id,
        "generation_mode": "concrete_fast_path",
        "project_archetype": "cli_toolkit",
    }


def non_web_project_provenance(project_id: str) -> dict[str, Any]:
    return concrete_fast_path_provenance(
        project_type=project_id,
        reason="bounded non-web concrete project matrix fast path",
    )


def _goal_excerpt(goal: str) -> str:
    cleaned = " ".join(str(goal or "").split())
    return cleaned[:220] if cleaned else "Non-web concrete project request"


def _readme(project_id: str, goal_text: str, run_command: str) -> str:
    return (
        f"# {project_id}\n\n"
        "Generated by ordinary CTCP project generation through `new-run/status/advance`.\n\n"
        "## Runtime\n\n"
        "- Python stdlib only.\n"
        f"- Run with `{run_command}`.\n"
        "- Run generated tests with `python -m unittest discover -v`.\n"
        "- No HTTP server or agent scaffold is required for this project.\n\n"
        "## Provenance\n\n"
        "- `provenance.json` records the bounded local materializer.\n\n"
        f"## Goal\n\n{_goal_excerpt(goal_text)}\n"
    )


CSV_APP = textwrap.dedent("""
from __future__ import annotations

import argparse, csv, json
from collections import defaultdict
from pathlib import Path


def analyze_expenses(path: Path) -> dict[str, object]:
    category = defaultdict(float)
    monthly = defaultdict(float)
    rows = 0
    with Path(path).open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            rows += 1
            amount = float(row.get("amount", "0") or 0)
            category[str(row.get("category", "uncategorized"))] += amount
            month = str(row.get("date", ""))[:7] or "unknown"
            monthly[month] += amount
    return {"row_count": rows, "category_totals": dict(category), "monthly_totals": dict(monthly)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    report = analyze_expenses(Path(args.input))
    Path(args.output).write_text(json.dumps(report, indent=2, sort_keys=True) + "\\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()

CSV_TESTS = textwrap.dedent("""
from __future__ import annotations

import json, subprocess, sys, tempfile, unittest
from pathlib import Path

from expense_analyzer import analyze_expenses


class ExpenseAnalyzerTests(unittest.TestCase):
    def test_analyze_and_cli(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            csv_path = Path(td) / "expenses.csv"
            out = Path(td) / "report.json"
            csv_path.write_text("date,category,amount\\n2026-01-05,Food,12.50\\n2026-01-09,Travel,20\\n2026-02-01,Food,7.50\\n", encoding="utf-8")
            self.assertEqual(analyze_expenses(csv_path)["category_totals"]["Food"], 20.0)
            proc = subprocess.run([sys.executable, "expense_analyzer.py", "--input", str(csv_path), "--output", str(out)], capture_output=True, text=True)
            self.assertEqual(proc.returncode, 0, proc.stderr)
            report = json.loads(out.read_text(encoding="utf-8"))
            self.assertEqual(report["monthly_totals"]["2026-01"], 32.5)


if __name__ == "__main__":
    unittest.main()
""").lstrip()

LOG_APP = textwrap.dedent("""
from __future__ import annotations

import argparse, json, re
from collections import Counter
from pathlib import Path

LEVELS = ("INFO", "WARN", "ERROR")


def analyze_log(path: Path) -> dict[str, object]:
    counts = Counter({level: 0 for level in LEVELS})
    errors = Counter()
    pattern = re.compile(r"\\b(INFO|WARN|ERROR)\\b[:\\s-]*(.*)")
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        match = pattern.search(line)
        if not match:
            continue
        level, message = match.group(1), match.group(2).strip()
        counts[level] += 1
        if level == "ERROR" and message:
            errors[message] += 1
    return {"level_counts": dict(counts), "top_errors": [{"message": msg, "count": count} for msg, count in errors.most_common(5)]}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args(argv)
    Path(args.output).write_text(json.dumps(analyze_log(Path(args.input)), indent=2) + "\\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()

LOG_TESTS = textwrap.dedent("""
from __future__ import annotations

import json, subprocess, sys, tempfile, unittest
from pathlib import Path

from log_analyzer import analyze_log


class LogAnalyzerTests(unittest.TestCase):
    def test_counts_and_cli(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            log = Path(td) / "sample.log"
            out = Path(td) / "summary.json"
            log.write_text("INFO started\\nWARN slow\\nERROR disk full\\nERROR disk full\\n", encoding="utf-8")
            self.assertEqual(analyze_log(log)["level_counts"]["ERROR"], 2)
            proc = subprocess.run([sys.executable, "log_analyzer.py", "--input", str(log), "--output", str(out)], capture_output=True, text=True)
            self.assertEqual(proc.returncode, 0, proc.stderr)
            summary = json.loads(out.read_text(encoding="utf-8"))
            self.assertEqual(summary["top_errors"][0]["message"], "disk full")


if __name__ == "__main__":
    unittest.main()
""").lstrip()

TEXT_INIT = "from .core import extract_keywords, normalize_whitespace, slugify, word_count\n\n__all__ = ['extract_keywords', 'normalize_whitespace', 'slugify', 'word_count']\n"
TEXT_CORE = textwrap.dedent("""
from __future__ import annotations

import re
from collections import Counter

STOPWORDS = {"a", "an", "and", "for", "in", "of", "or", "the", "to"}


def normalize_whitespace(text: str) -> str:
    return re.sub(r"\\s+", " ", str(text or "")).strip()


def slugify(text: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "-", normalize_whitespace(text).lower())
    return cleaned.strip("-")


def word_count(text: str) -> int:
    return len(re.findall(r"[A-Za-z0-9']+", str(text or "")))


def extract_keywords(text: str, limit: int = 5) -> list[str]:
    words = [w.lower() for w in re.findall(r"[A-Za-z0-9']+", str(text or "")) if w.lower() not in STOPWORDS]
    return [word for word, _count in Counter(words).most_common(limit)]
""").lstrip()
TEXT_TESTS = textwrap.dedent("""
from __future__ import annotations

import unittest

from text_utils import extract_keywords, normalize_whitespace, slugify, word_count


class TextUtilsTests(unittest.TestCase):
    def test_text_helpers(self) -> None:
        self.assertEqual(slugify(" Hello, CTCP World! "), "hello-ctcp-world")
        self.assertEqual(word_count("one two two"), 3)
        self.assertEqual(normalize_whitespace(" a\\n b\\t c "), "a b c")
        self.assertEqual(extract_keywords("alpha beta alpha the beta gamma")[0], "alpha")


if __name__ == "__main__":
    unittest.main()
""").lstrip()

QUIZ_APP = textwrap.dedent("""
from __future__ import annotations

import argparse, json
from pathlib import Path


def load_questions(path: Path) -> list[dict[str, object]]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return data["questions"] if isinstance(data, dict) else data


def score_answers(questions: list[dict[str, object]], answers: list[str]) -> dict[str, object]:
    correct = 0
    details = []
    for index, question in enumerate(questions):
        expected = str(question.get("answer", "")).strip().upper()
        actual = answers[index].strip().upper() if index < len(answers) else ""
        ok = actual == expected
        correct += int(ok)
        details.append({"question": index + 1, "answer": actual, "expected": expected, "correct": ok})
    return {"score": correct, "total": len(questions), "details": details}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--questions", required=True)
    parser.add_argument("--test-mode", action="store_true")
    parser.add_argument("--answers", default="")
    args = parser.parse_args(argv)
    questions = load_questions(Path(args.questions))
    if args.test_mode:
        print(json.dumps(score_answers(questions, [x for x in args.answers.split(",") if x]), sort_keys=True))
        return 0
    answers = []
    for question in questions:
        print(question["prompt"])
        for key, value in dict(question.get("choices", {})).items():
            print(f"{key}. {value}")
        answers.append(input("Answer: "))
    result = score_answers(questions, answers)
    print(f"Score: {result['score']}/{result['total']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
""").lstrip()

QUIZ_TESTS = textwrap.dedent("""
from __future__ import annotations

import json, subprocess, sys, tempfile, unittest
from pathlib import Path

from quiz_game import load_questions, score_answers


class QuizGameTests(unittest.TestCase):
    def test_score_and_test_mode(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "questions.json"
            path.write_text(json.dumps({"questions": [{"prompt": "2+2?", "choices": {"A": "3", "B": "4"}, "answer": "B"}]}), encoding="utf-8")
            self.assertEqual(score_answers(load_questions(path), ["B"])["score"], 1)
            proc = subprocess.run([sys.executable, "quiz_game.py", "--questions", str(path), "--test-mode", "--answers", "B"], capture_output=True, text=True)
            self.assertEqual(proc.returncode, 0, proc.stderr)
            self.assertEqual(json.loads(proc.stdout)["score"], 1)


if __name__ == "__main__":
    unittest.main()
""").lstrip()


def non_web_project_files(*, goal_text: str, project_id: str, project_root: str, workflow_doc_rel: str, context_used: list[str], project_archetype: str) -> dict[str, str]:
    del context_used, project_archetype
    provenance = non_web_project_provenance(project_id)
    common = standard_support_files(
        project_id=project_id,
        workflow_doc_rel=workflow_doc_rel,
        provenance=provenance,
        project_archetype="cli_toolkit",
        core_notes=f"# Core Runtime Notes\n\n- project_id: {project_id}\n- runtime: non_web_local\n- ordinary_mainline: new-run/status/advance/source_generation\n",
        workflow_notes=f"# {project_id} Workflow\n\n- Generate local non-web source files.\n- Run generated unittest suite.\n- Validate CLI/package behavior with deterministic local inputs.\n",
    )
    if project_id == "csv_expense_analyzer":
        files = {"README.md": _readme(project_id, goal_text, "python expense_analyzer.py --input sample_expenses.csv --output report.json"), "expense_analyzer.py": CSV_APP, "tests/test_expense_analyzer.py": CSV_TESTS, "sample_expenses.csv": "date,category,amount\n2026-01-05,Food,12.50\n2026-01-09,Travel,20\n2026-02-01,Food,7.50\n", "tests/__init__.py": "# generated test package\n", **common}
    elif project_id == "log_analyzer_cli":
        files = {"README.md": _readme(project_id, goal_text, "python log_analyzer.py --input sample.log --output summary.json"), "log_analyzer.py": LOG_APP, "tests/test_log_analyzer.py": LOG_TESTS, "sample.log": "INFO started\nWARN slow response\nERROR disk full\nERROR disk full\n", "tests/__init__.py": "# generated test package\n", **common}
    elif project_id == "text_utils_package":
        files = {"README.md": _readme(project_id, goal_text, "python -m unittest discover -v"), "text_utils/__init__.py": TEXT_INIT, "text_utils/core.py": TEXT_CORE, "tests/test_text_utils.py": TEXT_TESTS, "tests/__init__.py": "# generated test package\n", **common}
    elif project_id == "terminal_quiz_game":
        questions = {"questions": [{"prompt": "What is 2 + 2?", "choices": {"A": "3", "B": "4", "C": "5"}, "answer": "B"}, {"prompt": "Which letter starts CTCP?", "choices": {"A": "C", "B": "T", "C": "P"}, "answer": "A"}]}
        files = {"README.md": _readme(project_id, goal_text, "python quiz_game.py --questions sample_questions.json --test-mode --answers B,A"), "quiz_game.py": QUIZ_APP, "tests/test_quiz_game.py": QUIZ_TESTS, "sample_questions.json": json.dumps(questions, indent=2) + "\n", "tests/__init__.py": "# generated test package\n", **common}
    else:
        return {}
    return prefixed_files(project_root, files)
